const Sdata = {
  shopItems: [
    {
      id: 7,
      cover: "https://m.media-amazon.com/images/I/71086C-0u1L._AC_UL480_FMwebp_QL65_.jpg",
      name: "Tea Light Candle Holder",
      price: "180",
      discount: "25",
    },
    {
      id: 8,
      cover: "https://m.media-amazon.com/images/I/81As0c2fDzS._AC_UL480_FMwebp_QL65_.jpg",
      name: "Handemade Rajasthani doll",
      price: "120",
      discount: "10",
    },
    {
      id: 9,
      cover: "https://m.media-amazon.com/images/I/81PxikOZzqL._AC_UL480_FMwebp_QL65_.jpg",
      name: "Handcrafted Elephant Candle ",
      price: "50",
      discount: "50 ",
    },
    {
      id: 10,
      cover: "https://m.media-amazon.com/images/I/91lpCZLeSSL._AC_UL480_FMwebp_QL65_.jpg",
      name: "Rajasthani decorative showpiece",
      price: "145",
      discount: "10 ",
    },
    {
      id: 11,
      cover: "https://m.media-amazon.com/images/I/71V1p1adhjL._AC_UL480_QL65_.jpg",
      name: "Gandhiji Wooden Chakra spin wheel",
      price: "280",
      discount: "20 ",
    },
    {
      id: 12,
      cover: "https://m.media-amazon.com/images/I/61KUhuMEhIL._AC_UL480_QL65_.jpg ",
      name: "Decorative Wall Hanging Bell",
      price: "400",
      discount: "20 ",
    },
    {
      id: 13,
      cover: "https://m.media-amazon.com/images/I/61t1QhuHNLL._AC_UL480_QL65_.jpg",
      name: "Bird Handmade Wall Decorative",
      price: "250",
      discount: "5 ",
    },
    {
      id: 14,
      cover: "https://m.media-amazon.com/images/I/712-jWrz2zL._AC_UL480_FMwebp_QL65_.jpg",
      name: "HandWoven Knitted Winnow",
      price: "120",
      discount: "10",
    },
    {
      id: 15,
      cover: "https://m.media-amazon.com/images/I/71eo1O5nkpL._AC_UL480_QL65_.jpg",
      name: "Woolen White Hanging Wall Decor",
      price: "115",
      discount: "12",
    },
    {
      id: 16,
      cover: "https://m.media-amazon.com/images/I/91drlGrn2-L._AC_UL480_QL65_.jpg",
      name: "Artificial Marigold Flower Hanging",
      price: "85",
      discount: "22",
    },
    {
      id: 17,
      cover: "https://m.media-amazon.com/images/I/81nvkWXqnAL._AC_UL480_QL65_.jpg",
      name: "Pastel Iron Plates",
      price: "75",
      discount: "10",
    },
    {
      id: 18,
      cover: "https://m.media-amazon.com/images/I/81ts3fez1ML._AC_UL480_QL65_.jpg",
      name: "Handmade Door Hangings",
      price: "65",
      discount: "15",
    },
  ],
}
export default Sdata
